//<------------ASSETS------------->//

//Get Assets
GET http://localhost:5000/api/v1/assets

###
//Add Asset
POST http://localhost:5000/api/v1/assets HTTP/1.1
content-type: application/json

{
    "asset_name": "Laptop",
    "asset_category": "Electronics",
    "asset_status": "Available",
    "asset_serial": "ABCD1234",
    "asset_purchasecost": "2500",
    "asset_warrantydate": "July 1 2020"
}

###
//Delete Asset
DELETE http://localhost:5000/api/v1/assets/5fd1cd2dd1dc877e649ce947

###
//Update Asset
PATCH http://localhost:5000/api/v1/assets/5fd1cd2dd1dc877e649ce947
content-type: application/json

{
    "asset_name": "Computer",
    "asset_category": "Electronics"

}


###
//<------- USERS-------->//

//Get Users
GET http://localhost:5000/api/v1/users

###
//Add User
POST http://localhost:5000/api/v1/users/register HTTP/1.1
content-type: application/json

{
    "first_name": "John12",
    "last_name": "Doe",
    "username": "johndoe12",
    "password": "abcd1234",
    "email": "johndoe12@example.com",
    "user_role": "user",
    "assets_borrowed": []

}

###

//try johndoe10@example.com not register, johndoe12@example.com not activated
POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
    "email": "johndoe11@example.com",
    "password": "abcd1234"
}

###

// logout works only if token in the bearer
POST http://localhost:5000/api/v1/users/logout


###
//Delete User
DELETE http://localhost:5000/api/v1/users/5fe1facb69c1ef3bbc38d3fd

###
//Update User
PATCH http://localhost:5000/api/v1/users/5fe1facb69c1ef3bbc38d3fd
content-type: application/json

{
    "first_name": "Jimmy",
    "username": "jimmydoe@example.com"

}