https://asset-spartan-api.herokuapp.com/api/v1/assets


###
GET https://asset-spartan-api.herokuapp.com/api/v1/users/allusers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZ2FiaXNheUBnbWFpbC5jb20iLCJ1c2VySWQiOiI1ZmY3ZjRiNzZkMTFhZjQyYTA2YWYyZWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MTAxMTMzMDQsImV4cCI6MTYxMDE5OTcwNH0.LImFxd2mg98SsHrhk4wuxj_IE5wti772xy_LQnKwltk

###
POST https://asset-spartan-api.herokuapp.com/api/v1/users/register HTTP/1.1
Content-Type: application/json

{
      "user_role": "admin",
      "first_name": "Aubrey",
      "last_name": "Gabisay",
      "username": "Judeedz1",
      "email": "aagabisay@gmail.com",
      "password" : "admin"
}

###
PATCH https://asset-spartan-api.herokuapp.com/api/v1/users/5ff7f230851f6f2f987a4846
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyZ2FiaXNheUBnbWFpbC5jb20iLCJ1c2VySWQiOiI1ZmY3ZjRiNzZkMTFhZjQyYTA2YWYyZWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MTAxMTMzMDQsImV4cCI6MTYxMDE5OTcwNH0.LImFxd2mg98SsHrhk4wuxj_IE5wti772xy_LQnKwltk
Content-Type: application/json

{
      "is_active": true
}


##activating user after creating
###
GET https://asset-spartan-api.herokuapp.com/api/v1/users/activate/b9Eu9OivGf9uI96Q


###log in user
###
POST https://asset-spartan-api.herokuapp.com/api/v1/users/login
Content-Type: application/json

{
      "email": "argabisay@gmail.com",
      "password": "admin"
}